- name: roboshop project creation with Ansible
  hosts: local
  connection: local
  become: yes
  vars:
    sg_id: sg-0a7b91aa77cf9de83
    ami_id: ami-0220d79f3f480ecf5
    domain_name: sandh.co.in
    env: dev
    action: create
    instances:
      - mongodb
      - catalogue
  tasks:
  - name: create EC2 instances
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      name: "{{ item }}-{{ env }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags: 
        Project: roboshop
        Component: {{ item }}
        Environment: {{ env }}
        Name: "{{ item }}-{{ env }}"
    loop : {{ instances }}
    register: ec2_output
    when: action == create
  - name: print the ec2_output
    ansible.builtin.debug:
      msg: {{ ec2_output }}
    when: action == "create"
  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instance[0].private_ip_address }}"
      wait: false
      overwrite: false
    loop: "{{ ec2_output.results }}"
    when: action == "create""
  - name: create r53 records # for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instance[0].public_ip_address }}"
      wait: false
    loop: "{{ ec2_output.results }}"
    when:
    - item.item == "frontend"
    - action == "create"
########Destory###########
  - name: delete r53 records for frontend
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}"
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when:
    - item.item == "frontend"
    - action == "destroy"
  - name: delete r53 records for instances
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}-{{ env }}.{{ domain_name }}"
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when: action == "destroy"
  - name: delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}.{{ env }}"
      wait: false
    loop: "{{ instances }}"
    when: action == "destroy"
