- name: Installing and configuring mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: Installing mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: present
  
  - name: starting mysql server services
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enable: yes
  
  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1