- name: Create EC2 instance
  hosts: all
  connection: local
  vars:
    sg_id: sg-0a7b91aa77cf9de83
    ami_id: ami-0220d79f3f480ecf5
    domain_name: sandh.co.in
    env: dev
    action: create
    instances:
    - mongodb
    - catalogue
  tasks:
  ####CREAE####
  - name: create EC2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output
    when: action == "create"
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
    when: action == "create"
    